version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      tiptap:
        patterns:
          - '@tiptap*'
      prisma:
        patterns:
          - '@prisma/client'
          - 'prisma'
      jest:
        patterns:
          - 'jest*'
      trpc:
        patterns:
          - '@trpc*'
