version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 50
    groups:
      dedent:
        patterns:
          - 'dedent'
          - '@types/dedent'
      multer:
        patterns:
          - 'multer'
          - '@types/multer'
      tiptap:
        patterns:
          - '@tiptap*'
      eslint:
        patterns:
          - '*eslint*'
      prisma:
        patterns:
          - '@prisma/client'
          - 'prisma'
      jest:
        patterns:
          - 'jest*'
      trpc:
        patterns:
          - '@trpc*'
      socketio:
        patterns:
          - '*socketio*'
      hocuspocus:
        patterns:
          - '*hocuspocus*'
      workbox:
        patterns:
          - '*workbox*'
      aws:
        patterns:
          - '@aws-sdk/*'
      sentry:
        patterns:
          - '@sentry/*'
      vite:
        patterns:
          - 'vite'
          - 'vite-*'
          - '@vitejs/*'
      astro:
        patterns:
          - '@astrojs/*'
          - 'astro'
      react:
        patterns:
          - 'react-dom'
          - '@types/react-dom'
          - 'react'
          - '@types/react'
          - 'react-is'
          - '@types/react-is'
      babel:
        patterns:
          - '@babel/*'
      y:
        patterns:
          - 'yjs'
          - 'yjs-*'
          - 'y-*'
      ai-sdk:
        patterns:
          - 'ai'
          - '@ai-sdk/*'
      ionic:
        patterns:
          - '@ionic/*'
          - 'ionicons'
      swc:
        patterns:
          - '@swc*'
    ignore:
      - dependency-name: 'nx'
      - dependency-name: '@nx*' # Ignored because nx must be upgraded through CLI
      - dependency-name: 'tldraw' # Ignored because tldraw must be bumped with service-worker cache
