version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20
    groups:
      tiptap:
        patterns:
          - '@tiptap*'
      eslint:
        patterns:
          - '*eslint*'
      prisma:
        patterns:
          - '@prisma/client'
          - 'prisma'
      jest:
        patterns:
          - 'jest*'
      trpc:
        patterns:
          - '@trpc*'
      socketio:
        patterns:
          - '*socketio*'
      hocuspocus:
        patterns:
          - '*hocuspocus*'
      workbox:
        patterns:
          - '*workbox*'
    ignore:
      - dependency-name: 'nx'
      - dependency-name: '@nx*'
